# Generated by Django 2.2.6 on 2019-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='insurance_number_type',
            field=models.CharField(max_length=50),
        ),
    ]
