# Generated by Django 2.2.6 on 2019-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medaskApp', '0002_auto_20191025_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='healthinsurance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='healthinsurance',
            name='insurance_company_id',
        ),
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
    ]
