# Generated by Django 2.2.6 on 2019-10-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medaskApp', '0004_auto_20191025_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthInsurance',
            new_name='CompanyInsurance',
        ),
    ]
